//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp2
{
    using System;
    using System.Collections.Generic;
    
    public partial class saddnes
    {
        public string Logo { get; set; }
        public string agstype { get; set; }
        public string Title { get; set; }
        public string Phone { get; set; }
        public int Priority { get; set; }
    }
}
